name = "Modpack"
author = "Sacer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edf3df71e9f431806f8fe3e53a6bc49a8ec798b362a1039f012d734e6510345e"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
