name = "Modpack"
author = "Sacer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37bcd09119c0bee0af09d97f05eabdda779bfd083262d87964c22e64f165b2ab"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
